#default image (docker best practices advice against using :latest tags, be advised)
image: gcc:7

stages:
  - build
  - test

#
## stage: build
#

.job_build_template: &build_tdef
  stage: build
  before_script:
    - apt update
    - apt install -y --no-install-recommends cmake
  script:
    - mkdir build
    - cd build
    - cmake ../C
    - make
    - make install
  tags:
    - cpu
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_build"
    when: on_success
    expire_in: 1h
    paths:
      - /usr/local/MemoryReliability
  dependencies: []


build:gcc-7:
  image: gcc:7
  <<: *build_tdef

build:gcc-6:
  image: gcc:6
  <<: *build_tdef

build:gcc-5:
  image: gcc:5
  <<: *build_tdef

build:gcc-4:
  image: gcc:4
  <<: *build_tdef

#
## stage: test
#

##
## WARNING: MemoryReliability requires 'msr' kernel module!
##
.job_test_template: &test_tdef
  stage: test
  script:
    - /usr/local/MemoryReliability -d -m 1024 -s 10 -o output.log -e output.err
    - sleep 120
    - /usr/local/
  tags:
    - cpu
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_test"
    when: on_success
    expire_in: 1h
    paths:
      - output.log
      - output.err

test:gcc-7:
  image: gcc:7
  <<: *test_tdef
  dependencies:
    - build:gcc-7

test:gcc-6:
  image: gcc:6
  <<: *test_tdef
  dependencies:
    - build:gcc-6

test:gcc-5:
  image: gcc:5
  <<: *test_tdef
  dependencies:
    - build:gcc-5

test:gcc-4:
  image: gcc:4
  <<: *test_tdef
  dependencies:
    - build:gcc-4


